requires 'Lock::File';
requires 'IO::Socket::SSL';
requires 'List::Util', '1.42';
requires 'Mojolicious';
requires 'Mojolicious::Plugin::Minion';
requires 'Devel::Cover';
requires 'Git::Repository';
requires 'JSON';
requires 'Lingua::EN::Tagger';
requires 'Moose';
requires 'Regexp::Common::profanity';
requires 'Test::Most';
requires 'Text::Aspell';
